### ISSUE TITLE
Common: JWTPublicKeyIncluder to put resource server public key in the access token

### ISSUE THREAD

**Issue by DGoAdorsys** [adorsys/secure-key-storage#28]
* Create a component to put resource server public key in the access token.
    * JWTPublicKeyIncluder
      * include(oAuthToken JWT, resourceServerPublicKey JWK): JWT
      * The name of the claim to include is "res_pub_key"

**Comment by francis-pouatcha** [comment]
Found new way of obtaining server public key: rfc7523
